sources:
  - name: development-threshold-subgraph
    handler:
      graphql:
        endpoint: https://subgraph.satsuma-prod.com/276a55924ce0/nucypher--102994/mainnet/api
    transforms:
      - autoPagination:
          validateSchema: true
  - name: threshold-staking-polygon
    handler:
      graphql:
        endpoint: https://api.studio.thegraph.com/query/24143/threshold-staking-polygon/0.1.1
    transforms:
      - autoPagination:
          validateSchema: true
  - name: simple
    handler:
      graphql:
        endpoint: https://api.studio.thegraph.com/query/24143/simple-pre-application/version/latest
documents:
  - ./src/scripts/utils/graphql/TACoAuthHistoryQuery.gql
  - ./src/scripts/utils/graphql/TACoOperators.gql
  - ./src/scripts/utils/graphql/PREOpsBeforeLegacyDeactQuery.gql
  - ./src/scripts/utils/graphql/StakeHistoryBetweenTwoDatesQuery.gql
  - ./src/scripts/utils/graphql/AuthHistoryBetweenTwoDatesQuery.gql
